### ISSUE TITLE
Filters and Masks

### ISSUE THREAD

**Issue by asd12345** [Longan-Labs/Arduino_CAN_BUS_MCP2515#4]
hi, i am new to github so i am not quite sure this is the best way to comunicate. My question is,
can you make a exapmle where you would use fliters and masks for CAN massages. For example, you have two arduino's
comunicating via CAN bus, one is only sending messages (messages with extended ID's) and the other is supposed to 
read only messages with specific ID's.

Thanks

**Comment by sidney2007** [comment]
https://github.com/Longan-Labs/Arduino_CAN_BUS_MCP2515/blob/master/examples/set_mask_filter_recv/set_mask_filter_recv.ino
